Tutaj opis wszystkich kroków, jakie wykonaliśmy w celu oczyszczenia i przygotowania danych

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import math
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.impute import SimpleImputer

url = 'winequality-red.csv'
df = pd.read_csv(url, sep=";")

In [22]:
df.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [21]:
print(df[df.apply(lambda x: x.astype(str).str.contains('_')).any(axis=1)])

Empty DataFrame
Columns: [fixed acidity, volatile acidity, citric acid, residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, density, pH, sulphates, alcohol, quality]
Index: []

In [16]:
traits_to_covert_type = ['citric acid', 'residual sugar', 'chlorides']

for column in traits_to_covert_type:
    df[column] = df[column].str.strip('-_')

In [17]:
for column in traits_to_covert_type:
    df[column] = df[column].astype('float64')

In [28]:
columns_list = df.columns.tolist()
for column in columns_list:
    print(f"Kolumna: {column}")
    print(df[column].describe())
    print('-------------------------------------')

Kolumna: fixed acidity
count    1599.000000
mean        8.319637
std         1.741096
min         4.600000
25%         7.100000
50%         7.900000
75%         9.200000
max        15.900000
Name: fixed acidity, dtype: float64
-------------------------------------
Kolumna: volatile acidity
count    1599.000000
mean        0.527821
std         0.179060
min         0.120000
25%         0.390000
50%         0.520000
75%         0.640000
max         1.580000
Name: volatile acidity, dtype: float64
-------------------------------------
Kolumna: citric acid
count    1599.000000
mean        0.270976
std         0.194801
min         0.000000
25%         0.090000
50%         0.260000
75%         0.420000
max         1.000000
Name: citric acid, dtype: float64
-------------------------------------
Kolumna: residual sugar
count    1599.000000
mean        2.538806
std         1.409928
min         0.900000
25%         1.900000
50%         2.200000
75%         2.600000
max        15.500000
Name: residual sugar, dtype: float64
-------------------------------------
Kolumna: chlorides
count    1599.000000
mean        0.087467
std         0.047065
min         0.012000
25%         0.070000
50%         0.079000
75%         0.090000
max         0.611000
Name: chlorides, dtype: float64
-------------------------------------
Kolumna: free sulfur dioxide
count    1599.000000
mean       15.756098
std        10.638410
min       -29.000000
25%         7.000000
50%        13.000000
75%        21.000000
max        72.000000
Name: free sulfur dioxide, dtype: float64
-------------------------------------
Kolumna: total sulfur dioxide
count    1599.000000
mean       46.467792
std        32.895324
min         6.000000
25%        22.000000
50%        38.000000
75%        62.000000
max       289.000000
Name: total sulfur dioxide, dtype: float64
-------------------------------------
Kolumna: density
count    1595.000000
mean        0.996751
std         0.001886
min         0.990070
25%         0.995600
50%         0.996750
75%         0.997845
max         1.003690
Name: density, dtype: float64
-------------------------------------
Kolumna: pH
count    1599.000000
mean        3.311113
std         0.154386
min         2.740000
25%         3.210000
50%         3.310000
75%         3.400000
max         4.010000
Name: pH, dtype: float64
-------------------------------------
Kolumna: sulphates
count    1599.000000
mean        0.658149
std         0.169507
min         0.330000
25%         0.550000
50%         0.620000
75%         0.730000
max         2.000000
Name: sulphates, dtype: float64
-------------------------------------
Kolumna: alcohol
count    1599.000000
mean       10.422983
std         1.065668
min         8.400000
25%         9.500000
50%        10.200000
75%        11.100000
max        14.900000
Name: alcohol, dtype: float64
-------------------------------------
Kolumna: quality
count    1599.000000
mean        5.636023
std         0.807569
min         3.000000
25%         5.000000
50%         6.000000
75%         6.000000
max         8.000000
Name: quality, dtype: float64
-------------------------------------

Sprawdzić odchylenia
Znormalizować dane